### ISSUE TITLE
jpk: KeyError '33027'

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/AFMReader#134]
We've received a report that when loading `.jpk` files the channel `33027` can not be found.

``` python
  File "/Users/<username>/20250416_ExportAFM.py", line 75, in <module>

    image, pixel_to_nm_scaling = load_jpk(FILE, channel=channels[chan])

                                 ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/<username>/anaconda3/envs/afmreader/lib/python3.13/site-packages/AFMReader/jpk.py", line 95, in load_jpk

    scaling_type = channel_page.tags["33027"].value

                   ~~~~~~~~~~~~~~~~~^^^^^^^^^

  File "/Users/<username>/anaconda3/envs/afmreader/lib/python3.13/site-packages/tifffile/tifffile.py", line 11927, in __getitem__

    raise KeyError(key)

KeyError: '33027'
```

It looks like this arises because the value of `chan` in the parameger `channel=channels[chan]` isn't recognised.

It's possible that one solution might be related to the tags and their mapping which we recently moved from being hard-coded to `AFMReader/default_config.yaml` and added an option to `jpk.load_jpk(..., config_path = <path_to_config.yaml>)` to allow users to specify their own configuration files with new tags from the wild that we have not encoutered previously.

Its possible that this could be the first case where this will help with that.

Currently the feature is not included in a tagged and published release so the version of AFMReader available on PyPI does not include this functionality.

It is possible to install the current features from GitHub directly though. As per our [installation instructions](https://afm-spm.github.io/AFMReader/installation/) the development version can be installed under a Virtual Environment (e.g. Conda) using..

``` shell
pip install git+https://github.com/AFM-SPM/AFMReader.git
```

A copy of the [`default_config.yaml`](https://github.com/AFM-SPM/AFMReader/blob/main/AFMReader/default_config.yaml) should be made to the working directory and the missing tag and value added. If for example `33027` corresponds to tag name `something` the `default_config.yaml` would look like this...

``` yaml
jpk:
  n_slots: 32896
  default_slot: 32897
  first_slot_tag: 32912
  first_scaling_type: 32931
  first_scaling_name: 32932
  first_offset_name: 32933
  channel_name: 32848
  trace_retrace: 32849
  grid_ulength: 32834
  grid_vlength: 32835
  grid_ilength: 32838
  grid_jlength: 32839
  slot_size: 48
  something: 33027
```

If this file is saved as `new_config.yaml` in the same directory as `20250416_ExportAFM.py` then, based on the code-snippet in the error message the path to this file should be added to the call to `load_jpk()`...

``` python
    image, pixel_to_nm_scaling = load_jpk(FILE, channel=channels[chan], config_path="new_config.yaml")
```

This is however untested.

Alternatively it could something else! We'll get to the bottom of it though.
