### ISSUE TITLE
Add pytest-testmon pre-commit hook

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/AFMReader#88]
We now use [pytest-testmon](https://github.com/tarpas/pytest-testmon/) as a [pre-commit](https://pre-commit.com) hook on
[AFM-SPM/TopoStats](https://github.com/AFM-SPM/TopoStats/) as it helps us remember to make sure we don't break any
existing tests when working on the code base.

It would therefore be useful to have it enabled in AFMReader.

## `pyproject.toml`

```toml
[project.optional-dependencies]
dev = [
  ...
  pytest-testmon,
  ...
]
```

## `.pre-commit-config.yaml`

```yaml
  - repo: local
    hooks:
      - id: pytest
        name: Pytest (testmon)
        entry: pytest --testmon
        language: system
        files: \.py$
```
