### ISSUE TITLE
Apply mypy in pre-commit/CI

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/AFMReader#96]
Typehints are already good in this codebase but it would be useful to add in [mypy](https://www.mypy-lang.org/) checks
via a pre-commit hook.

``` yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports] # default but useful to be explicit
```

To help with this we can try running [RighTyper](https://github.com/RightTyper/RightTyper) against the code base as it
analyses and informs what the typehints should be for a code base. It only works with Python >= 3.12 though (and
currently we can not support Python >= 3.12 with TopoStats due to as yet unresolved issues with the `topoly` dependency,
see [Performance regression of Topoly with Python 3.12 · Issue #927 ·
AFM-SPM/TopoStats](https://github.com/AFM-SPM/TopoStats/issues/927)). However we should be able to add support for
Python 3.12 in AFMReader.

- [x] #97
